name = "signature-event"
compatibility_date = "2024-10-10"

[assets]
directory = "."
binding = "ASSETS"

[env.production]
name = "signature-event-prod"

[[env.production.rules]]
type = "Headers"
globs = ["/_headers"]

[[env.production.rules]]
type = "Redirects"
globs = ["/_redirects"]